[colors.primary]
foreground = "#a6a499"
background = "#131515"
dim_foreground = "#a69a8d"

[colors.normal]
black =     "#222625"
red =       "#e74e3d"
green =     "#9aad6c"
yellow =    "#f6ba41"
blue =      "#879291"
magenta =   "#ee617b"
cyan =      "#fe7442"
white =     "#a6a499"

[colors.bright]
black =     "#59544d"
red =       "#e74e3d"
green =     "#b1ca78"
yellow =    "#fe7442"
blue =      "#82979c"
magenta =   "#ee617b"
cyan =      "#e74e3d"
white =     "#a69a8d"
