local M = {}

function M.get(pallet)
  return {
    ColorColumn                 = { bg = pallet.background3 },
    Conceal                     = { fg = pallet.comment },

    Cursor                      = { fg = pallet.cursor_under_txt, bg = pallet.cursor },
    iCursor                     = { fg = pallet.cursor_under_txt, bg = pallet.cursor },
    vCursor                     = { fg = pallet.cursor_under_txt, bg = pallet.cursor },
    lCursor                     = { fg = pallet.cursor_under_txt, bg = pallet.cursor },
    CursorIM                    = { fg = pallet.cursor_under_txt, bg = pallet.cursor },
    CursorColumn                = { bg = pallet.background3 },
    CursorLine                  = { bg = pallet.background3 },

    Directory                   = { fg = pallet.operator },
    DiffAdd                     = { fg = pallet.namespace },
    DiffChange                  = { fg = pallet.type },
    DiffDelete                  = { fg = pallet.keyword },
    DiffText                    = { fg = pallet.functions },

    EndOfBuffer                 = { fg = pallet.background3 },

    TermCursor                  = { link = "Cursor" },
    TermCursorNC                = { link = "Comment" },

    ErrorMsg                    = { fg = pallet.keyword },
    WinSeparator                = { fg = pallet.background3 },

    Folded                      = { fg = pallet.comment },
    FoldColumn                  = { fg = pallet.background3 },
    SignColumn                  = { fg = pallet.background3 },

    IncSearch                   = { fg = pallet.type },
    CurSearch                   = { link = "IncSearch" },

    LineNr                      = { fg = pallet.comment },
    MatchParen                  = { bg = pallet.comment },

    ModeMsg                     = { fg = pallet.namespace, bg = pallet.background2 },
    MsgArea                     = { bg = pallet.background2 },
    MsgSeparator                = { fg = pallet.background3 },
    MoreMsg                     = { fg = pallet.string, bg = pallet.background2 },

    VertSplit                   = { fg = pallet.text, bg = pallet.background1, },

    Substitute                  = { fg = pallet.cursor_under_txt, bg = pallet.type },
    CursorLineNr                = { fg = pallet.text2 },

    NonText                     = { fg = pallet.keyword },
    Normal                      = { fg = pallet.text, bg = pallet.background1 },
    NormalFloat                 = { fg = pallet.text, bg = pallet.background1 },
    FloatBorder                 = { fg = pallet.comment },
    FloatTitle                  = { fg = pallet.functions, bold = true },

    Pmenu                       = { bg = pallet.background2 },
    PmenuSel                    = { link = "CursorLine" },
    PmenuKind                   = { fg = pallet.type },
    PmenuKindSel                = { fg = pallet.type },
    PmenuSBar                   = { bg = pallet.comment },
    PmenuThumb                  = { bg = pallet.comment },

    Question                    = { fg = pallet.namespace, bold = true },
    QuickFixLine                = { fg = pallet.namespace },
    Search                      = { fg = pallet.cursor_under_txt, bg = pallet.type },
    SpecialKey                  = { fg = "NONE", bg = "NONE" },

    SpellBad                    = { undercurl = true, sp = pallet.keyword },

    StatusLine                  = { bg = pallet.background2 },
    StatusLineNC                = { fg = pallet.comment, bg = pallet.background2 },

    TabLine                     = { bg = pallet.background2 },
    TabLineFill                 = { bg = pallet.background2 },
    TabLineSel                  = { bg = pallet.background2 },

    Title                       = { fg = pallet.functions, bold = true },
    Visual                      = { bg = pallet.background3 },
    VisualNOS                   = { bg = pallet.background3 },
    WarningMsg                  = { fg = pallet.type },

    Whitespace                  = { fg = pallet.comment },
    Winseparator                = { fg = pallet.background3 },
    WildMenu                    = { fg = pallet.cursor_under_txt, bg = pallet.type },
    WinBar                      = { fg = pallet.background3, bg = pallet.background3 },
    WinBarNC                    = { fg = pallet.background3, bg = pallet.background3 },

    -- Common
    Comment                     = { fg = pallet.comment, italic = true },

    Constant                    = { fg = pallet.constant },
    String                      = { fg = pallet.string },
    Character                   = { fg = pallet.constant },
    Number                      = { fg = pallet.constant },
    Boolean                     = { fg = pallet.constant },
    Float                       = { fg = pallet.constant },

    Identifier                  = { fg = pallet.property },
    Function                    = { fg = pallet.functions, italic = true },

    Statement                   = { fg = pallet.keyword },
    Conditional                 = { fg = pallet.keyword },
    Repeat                      = { fg = pallet.keyword },
    Label                       = { fg = pallet.keyword },
    Operator                    = { fg = pallet.operator },
    Keyword                     = { fg = pallet.keyword },
    Exception                   = { fg = pallet.keyword },

    PreProc                     = { fg = pallet.text2 },
    Include                     = { fg = pallet.text2 },
    Define                      = { fg = pallet.text2 },
    Macro                       = { fg = pallet.constant },
    PreCondit                   = { fg = pallet.text2 },

    Type                        = { fg = pallet.keyword },
    StorageClass                = { fg = pallet.keyword },
    Structure                   = { fg = pallet.type },
    Typedef                     = { fg = pallet.type },

    Special                     = { fg = pallet.constant },
    SpecialChar                 = { fg = pallet.constant },
    Tag                         = { fg = pallet.keyword },
    Delimiter                   = { fg = pallet.text2 },
    SpecialComment              = { fg = pallet.operator },
    Debug                       = { fg = pallet.type },

    Underlined                  = { fg = pallet.keyword, underline = true },
    Ignore                      = { fg = pallet.comment },
    Error                       = { fg = pallet.keyword },
    Todo                        = { bg = pallet.operator },

    DiagnosticError             = { fg = pallet.keyword },
    DiagnosticWarn              = { fg = pallet.type },
    DiagnosticInfo              = { fg = pallet.string },
    DiagnosticHint              = { fg = pallet.operator },
    DiagnosticSignError         = { fg = pallet.keyword },
    DiagnosticSignWarn          = { fg = pallet.type },
    DiagnosticSignInfo          = { fg = pallet.string },
    DiagnosticSignHint          = { fg = pallet.operator },
    DiagnosticUnderlineError    = { undercurl = true, sp = pallet.keyword },
    DiagnosticUnderlineWarn     = { undercurl = true, sp = pallet.type },
    DiagnosticUnderlineInfo     = { undercurl = true, sp = pallet.string },
    DiagnosticUnderlineHint     = {},
    DiagnosticFloatingError     = { fg = pallet.keyword },
    DiagnosticFloatingWarn      = { fg = pallet.type },
    DiagnosticFloatingInfo      = { fg = pallet.string },
    DiagnosticFloatingHint      = { fg = pallet.operator },
    DiagnosticTextError         = { fg = pallet.keyword },
    DiagnosticTextWarn          = { fg = pallet.type },
    DiagnosticTextInfo          = { fg = pallet.string },
    DiagnosticTextHint          = {},

    LspReferenceText            = { fg = pallet.keyword, bold = true },
    LspReferenceRead            = { fg = pallet.keyword, bold = true },
    LspReferenceWrite           = { fg = pallet.functions, bold = true },
    LspCodeLens                 = { fg = pallet.operator },
    LspSignatureActiveParameter = { bg = pallet.background3 },
    LspInlayHint                = { link = "Comment" },

    ["@none"]                   = { fg = "NONE", bg = "NONE" },

    ["@text"]                   = { link = "Normal" },
    ["@text.strong"]            = { bold = true },
    ["@text.emphasis"]          = { italic = true },
    ["@text.underline"]         = { link = "Underlined" },
    ["@text.strike"]            = { strikethrough = true },
    ["@text.literal"]           = { link = "String" },
    ["@text.reference"]         = { link = "Constant" },
    ["@text.math"]              = { fg = pallet.operator },
    ["@text.environment"]       = { link = "Macro" },
    ["@text.environment.name"]  = { link = "@text" },
    ["@text.title"]             = { link = "Title" },
    ["@text.uri"]               = { link = "Underlined" },
    ["@text.todo"]              = { link = "Todo" },
    ["@text.note"]              = { link = "SpecialComment" },
    ["@text.warning"]           = { link = "WarningMsg" },
    ["@text.danger"]            = { link = "ErrorMsg" },
    ["@text.danger.comment"]    = { link = "ErrorMsg" },
    ["@text.diff.add"]          = { link = "DiffAdd" },
    ["@text.diff.delete"]       = { link = "DiffDelete" },

    ["@tag"]                    = { link = "Tag" },
    ["@tag.attribute"]          = { link = "Identifier" },
    ["@tag.delimiter"]          = { link = "Delimiter" },

    ["@punctuation"]            = { link = "Delimiter" },
    ["@punctuation.bracket"]    = { link = "Delimiter" },
    ["@punctuation.special"]    = { link = "Special" },

    ["@lsp.type.class"]         = { link = "Structure" },
    ["@lsp.type.comment"]       = { link = "@comment" },
    ["@lsp.type.decorator"]     = { link = "@macro" },
    ["@lsp.type.enum"]          = { link = "@structure" },
    ["@lsp.type.enumMember"]    = { fg = pallet.namespace },
    ["@lsp.type.function"]      = { link = "@function" },
    ["@lsp.type.interface"]     = { link = "Identifier" },
    ["@lsp.type.macro"]         = { link = "@macro" },
    ["@lsp.type.method"]        = { link = "@method" },
    ["@lsp.type.namespace"]     = { link = "@namespace" },
    ["@lsp.type.parameter"]     = { link = "@parameter" },
    ["@lsp.type.property"]      = { link = "@property" },
    ["@lsp.type.struct"]        = { link = "@structure" },
    ["@lsp.type.type"]          = { link = "@type.definition" },
    ["@lsp.type.TypeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"]      = { link = "@variable" },

    ["@comment"]                = { link = "Comment" },
    ["@constant"]               = { link = "Constant" },
    ["@constant.builtin"]       = { link = "Constant" },
    ["@constant.macro"]         = { link = "Define" },
    ["@define"]                 = { link = "Define" },
    ["@macro"]                  = { link = "Macro" },
    ["@string"]                 = { link = "String" },
    ["@string.escape"]          = { link = "Special" },
    ["@string.special"]         = { link = "SpecialChar" },
    ["@string.regex"]           = { link = "SpecialChar" },
    ["@character"]              = { link = "String" },
    ["@character.special"]      = { link = "SpecialChar" },
    ["@number"]                 = { link = "Number" },
    ["@boolean"]                = { link = "Boolean" },
    ["@float"]                  = { link = "Float" },
    ["@function"]               = { link = "Function" },
    ["@function.call"]          = { link = "Function" },
    ["@function.builtin"]       = { link = "Function" },
    ["@function.macro"]         = { link = "Macro" },
    ["@parameter"]              = { fg = pallet.parameter },
    ["@method"]                 = { link = "Function" },
    ["@method.call"]            = { link = "Function" },
    ["@field"]                  = { fg = pallet.property },
    ["@property"]               = { fg = pallet.property },
    ["@constructor"]            = { link = "Delimiter" },
    ["@conditional"]            = { link = "Conditional" },
    ["@repeat"]                 = { link = "Repeat" },
    ["@label"]                  = { link = "Label" },
    ["@operator"]               = { link = "Operator" },
    ["@keyword"]                = { link = "Keyword" },
    ["@keyword.operator"]       = { link = "Operator" },
    ["@keyword.return"]         = { link = "Keyword" },
    ["@exception"]              = { link = "Exception" },
    ["@variable"]               = { fg = pallet.variable },
    ["@variable.builtin"]       = { link = "Special" },
    ["@storageclass"]           = { link = "StorageClass" },
    ["@structure"]              = { link = "Structure" },
    ["@namespace"]              = { fg = pallet.namespace },
    ["@type"]                   = { link = "Type" },
    ["@type.builtin"]           = { link = "Type" },
    ["@type.definition"]        = { link = "Typedef" },
    ["@type.qualifier"]         = { link = "Keyword" },
    ["@include"]                = { link = "Include" },
    ["@preproc"]                = { link = "PreProc" },
    ["@debug"]                  = { link = "Debug" },

    NvimTreeNormal              = { bg = pallet.background2 },
    NvimTreeSymlink             = { fg = pallet.variable },
    NvimTreeRootFolder          = { fg = pallet.functions, bold = true },
    NvimTreeFolderIcon          = { fg = pallet.operator, bold = true },
    NvimTreeFileIcon            = { fg = pallet.text },
    NvimTreeExecFile            = { fg = pallet.namespace, bold = true },
    NvimTreeOpenedFile          = { fg = pallet.keyword, bold = true },
    NvimTreeSpecialFile         = { fg = pallet.type, bold = true, underline = true },
    NvimTreeImageFile           = { fg = pallet.constant },
    NvimTreeIndentMarker        = { fg = pallet.background3 },
    NvimTreeGitDirty            = { fg = pallet.keyword },
    NvimTreeGitStaged           = { fg = pallet.namespace },
    NvimTreeGitMerge            = { fg = pallet.functions },
    NvimTreeGitRenamed          = { fg = pallet.functions },
    NvimTreeGitNew              = { fg = pallet.namespace },
    NvimTreeGitDeleted          = { fg = pallet.keyword },
    NvimTreeWindowPicker        = { fg = pallet.cursor_under_txt, bg = pallet.operator },

    debugPC                     = { bg = pallet.operator },
    debugBreakpoint             = { fg = pallet.keyword },

    TelescopeNormal             = { link = "Normal" },
    TelescopePromptNormal       = { link = "Normal" },
    TelescopeBorder             = { link = "FloatBorder" },
    TelescopePromptBorder       = { link = "FloatBorder" },
    TelescopePromptTitle        = { link = "Title" },
    TelescopePreviewTitle       = { link = "Title" },
    TelescopeResultsTitle       = { link = "Title" },
    TelescopeMatching           = { fg = pallet.type, bold = true },
    TelescopePromptPrefix       = { fg = pallet.keyword, bg = pallet.background3 },
    TelescopeSelectionCaret     = { fg = pallet.functions, bg = pallet.background3 },
    TelescopeSelection          = { fg = pallet.functions, bg = pallet.background3 },

    CmpItemAbbrMatch            = { fg = pallet.type },
    CmpItemAbbrMatchFuzzy       = { fg = pallet.functions },
    CmpItemKindArray            = { fg = pallet.text2 },
    CmpItemKindBoolean          = { link = "Keyword" },
    CmpItemKindClass            = { link = "Structure" },
    CmpItemKindColor            = { fg = pallet.operator },
    CmpItemKindConstant         = { link = "Constant" },
    CmpItemKindConstructor      = { link = "Structure" },
    CmpItemKindCopilot          = { fg = pallet.operator },
    CmpItemKindEnum             = { link = "Structure" },
    CmpItemKindEnumMember       = { fg = pallet.namespace },
    CmpItemKindEvent            = { link = "Normal" },
    CmpItemKindField            = { fg = pallet.property },
    CmpItemKindFile             = { link = "Normal" },
    CmpItemKindFolder           = { link = "Directory" },
    CmpItemKindPackage          = { link = "Directory" },
    CmpItemKindProperty         = { fg = pallet.property },
    CmpItemKindText             = { link = "Normal" },
    CmpItemKindFunction         = { fg = pallet.functions },
    CmpItemKindInterface        = { link = "Identifier" },
    CmpItemKindKeyword          = { link = "Keyword" },
    CmpItemKindReference        = { fg = pallet.operator },
    CmpItemKindTypeParameter    = { link = "Type" },
    CmpItemKindMethod           = { fg = pallet.functions },
    CmpItemKindModule           = { fg = pallet.namespace },
    CmpItemKindNamespace        = { fg = pallet.namespace },
    CmpItemKindNull             = { link = "Constant" },
    CmpItemKindNumber           = { link = "Number" },
    CmpItemKindObject           = { link = "Structure" },
    CmpItemKindStruct           = { link = "Structure" },
    CmpItemKindOperator         = { link = "Operator" },
    CmpItemKindSnippet          = { fg = pallet.operator },
    CmpItemKindString           = { link = "String" },
    CmpItemKindUnit             = { link = "String" },
    CmpItemKindValue            = { link = "Constant" },
    CmpItemKindVariable         = { fg = pallet.variable },

    CocErrorSign                = { link = "DiagnosticError" },
    CocWarningSign              = { link = "DiagnosticWarn" },
    CocInfoSign                 = { link = "DiagnosticSignInfo" },
    CocHintSign                 = { link = "DiagnosticSignHint" },
    CocErrorFloat               = { link = "DiagnosticFloatingError" },
    CocWarningFloat             = { link = "DiagnosticFloatingWarn" },
    CocInfoFloat                = { link = "DiagnosticFloatingInfo" },
    CocHintFloat                = { link = "DiagnosticFloatingHint" },
    CocDiagnosticsError         = { link = "DiagnosticError" },
    CocDiagnosticsWarning       = { link = "DiagnosticWarn" },
    CocDiagnosticsInfo          = { link = "DiagnosticInfo" },
    CocDiagnosticsHint          = { link = "DiagnosticHint" },
    CocSelectedText             = { fg = pallet.type },
    CocMenuSel                  = { link = "PmenuSel" },
    CocCodeLens                 = { fg = pallet.operator },
    CocErrorHighlight           = { undercurl = true, sp = pallet.keyword },
    CocWarningHighlight         = { undercurl = true, sp = pallet.type },
    CocInfoHighlight            = { undercurl = true, sp = pallet.string },
    CocHintHighlight            = { undercurl = true, sp = pallet.operator },

    -- htmlTag                     = { link = "Keyword" },
    -- htmlEndTag                  = { link = "Keyword" },
    -- htmlTagName                 = { link = "Variable" },
    -- htmlArg                     = { fg = pallet.parameter },
    -- htmlTagN                    = { link = "Normal" },
    -- htmlSpecialTagName          = { link = "Variable" },
    -- htmlLink                    = { fg = pallet.operator, underline = config.underline },
    -- htmlSpecialChar             = { link = "Keyword" },
    -- htmlBold                    = { bold = config.bold },
    -- htmlBoldUnderline           = { bold = config.bold, underline = config.underline },
    -- htmlBoldItalic              = { bold = config.bold, italic = true },
    -- htmlBoldUnderlineItalic     = {
    --   fg = colors.fg0,
    --   bg = colors.bg0,
    --   bold = config.bold,
    --   italic = true,
    --   underline = config.underline,
    -- },
    -- htmlUnderline               = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    -- htmlUnderlineItalic         = {
    --   fg = colors.fg0,
    --   bg = colors.bg0,
    --   italic = true,
    --   underline = config.underline,
    -- },
    -- htmlItalic                  = { fg = colors.fg0, bg = colors.bg0, italic = true },
    -- xmlTag                      = { link = "GruvboxAquaBold" },
    -- xmlEndTag                   = { link = "GruvboxAquaBold" },
    -- xmlTagName                  = { link = "GruvboxBlue" },
    -- xmlEqual                    = { link = "GruvboxBlue" },
    -- docbkKeyword                = { link = "GruvboxAquaBold" },
    -- xmlDocTypeDecl              = { link = "GruvboxGray" },
    -- xmlDocTypeKeyword           = { link = "GruvboxPurple" },
    -- xmlCdataStart               = { link = "GruvboxGray" },
    -- xmlCdataCdata               = { link = "GruvboxPurple" },
    -- dtdFunction                 = { link = "GruvboxGray" },
    -- dtdTagName                  = { link = "GruvboxPurple" },
    -- xmlAttrib                   = { link = "GruvboxOrange" },
    -- xmlProcessingDelim          = { link = "GruvboxGray" },
    -- dtdParamEntityPunct         = { link = "GruvboxGray" },
    -- dtdParamEntityDPunct        = { link = "GruvboxGray" },
    -- xmlAttribPunct              = { link = "GruvboxGray" },
    -- xmlEntity                   = { link = "GruvboxRed" },
    -- xmlEntityPunct              = { link = "GruvboxRed" },
  }
end

return M
